# Generated by Django 4.0.5 on 2022-07-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='subject',
            new_name='message',
        ),
    ]
